const UPDATE_QUERYS_SEARCH = "UPDATE_QUERYS_SEARCH"
const UPDATE_QUERYS_PAGINATE = "UPDATE_QUERYS_PAGINATE"
const UPDATE_QUERYS_FILTER = "UPDATE_QUERYS_FILTER"
const UPDATE_QUERYS_ORDER = "UPDATE_QUERYS_ORDER"
const UPDATE_URL = "UPDATE_URL"
const UPDATE_CURRENT_PAGE = "SET_CURRENT_PAGE"
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"

export {
    UPDATE_QUERYS_FILTER,
    UPDATE_QUERYS_ORDER,
    UPDATE_QUERYS_PAGINATE,
    UPDATE_QUERYS_SEARCH,
    UPDATE_URL,
    UPDATE_CURRENT_PAGE,
    GET_ALL_PRODUCTS
}