const UPDATE_QUERYS_SEARCH = "UPDATE_QUERYS_SEARCH"
const UPDATE_QUERYS_PAGINATE = "UPDATE_QUERYS_PAGINATE"
const UPDATE_QUERYS_FILTER = "UPDATE_QUERYS_FILTER"
const UPDATE_URL = "UPDATE_URL"
const UPDATE_CURRENT_PAGE = "SET_CURRENT_PAGE"
export {
    UPDATE_QUERYS_FILTER,
    UPDATE_QUERYS_PAGINATE,
    UPDATE_QUERYS_SEARCH,
    UPDATE_URL,
    UPDATE_CURRENT_PAGE
}