const UPDATE_QUERYS_SEARCH = "UPDATE_QUERYS_SEARCH";
const UPDATE_QUERYS_PAGINATE = "UPDATE_QUERYS_PAGINATE";
const UPDATE_QUERYS_FILTER = "UPDATE_QUERYS_FILTER";
const UPDATE_QUERYS_ORDER = "UPDATE_QUERYS_ORDER";
const UPDATE_URL = "UPDATE_URL";
const UPDATE_CURRENT_PAGE = "SET_CURRENT_PAGE";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_PRODUCT_ID = "GET_PRODUCT_ID";

const GET_USER = "GET_USER";
const ERROR = "ERROR";
const LOGIN_USER = "LOGIN_USER";
const REGISTER_USER = "REGISTER_USER";
const LOGOUT_USER = "LOGOUT_USER";

export {
  UPDATE_QUERYS_FILTER,
  UPDATE_QUERYS_ORDER,
  UPDATE_QUERYS_PAGINATE,
  UPDATE_QUERYS_SEARCH,
  UPDATE_URL,
  UPDATE_CURRENT_PAGE,
  GET_ALL_PRODUCTS,
  GET_PRODUCT_ID,
  GET_USER,
  LOGIN_USER,
  REGISTER_USER,
  LOGOUT_USER,
  ERROR,
};
